"""
Feature loading and preparation for model training.

Loads feature-engineered CSV files generated by notebooks/03_feature_engineering.ipynb.
"""

from pathlib import Path

from loguru import logger
import pandas as pd
import typer

from urban_mobility_forecaster.config import (
    FEATURE_COLUMNS,
    TARGET_COLUMN,
    TEST_FEATURES_FILE,
    TRAIN_FEATURES_FILE,
    VAL_FEATURES_FILE,
)

app = typer.Typer()


def load_features(
    train_file: Path = TRAIN_FEATURES_FILE,
    val_file: Path = VAL_FEATURES_FILE,
    test_file: Path = TEST_FEATURES_FILE,
):
    """Load feature-engineered datasets from CSV files."""
    logger.info(f"Loading training features from {train_file}...")
    train_df = pd.read_csv(train_file)
    
    logger.info(f"Loading validation features from {val_file}...")
    val_df = pd.read_csv(val_file)
    
    logger.info(f"Loading test features from {test_file}...")
    test_df = pd.read_csv(test_file)
    
    logger.info(f"Train shape: {train_df.shape}")
    logger.info(f"Val shape: {val_df.shape}")
    logger.info(f"Test shape: {test_df.shape}")
    
    return train_df, val_df, test_df


def prepare_features(train_df, val_df, test_df):
    """Extract features and target from datasets."""
    X_train = train_df[FEATURE_COLUMNS].copy()
    y_train = train_df[TARGET_COLUMN].copy()
    
    X_val = val_df[FEATURE_COLUMNS].copy()
    y_val = val_df[TARGET_COLUMN].copy()
    
    X_test = test_df[FEATURE_COLUMNS].copy()
    y_test = test_df[TARGET_COLUMN].copy()
    
    logger.info(f"X_train shape: {X_train.shape}, y_train shape: {y_train.shape}")
    logger.info(f"X_val shape: {X_val.shape}, y_val shape: {y_val.shape}")
    logger.info(f"X_test shape: {X_test.shape}, y_test shape: {y_test.shape}")
    
    # Check for missing values
    missing_train = X_train.isnull().sum().sum()
    missing_val = X_val.isnull().sum().sum()
    missing_test = X_test.isnull().sum().sum()
    
    if missing_train > 0:
        logger.warning(f"Training set has {missing_train} missing values - filling with 0")
        X_train = X_train.fillna(0)
    if missing_val > 0:
        logger.warning(f"Validation set has {missing_val} missing values - filling with 0")
        X_val = X_val.fillna(0)
    if missing_test > 0:
        logger.warning(f"Test set has {missing_test} missing values - filling with 0")
        X_test = X_test.fillna(0)
    
    return X_train, y_train, X_val, y_val, X_test, y_test


@app.command()
def main(
    train_file: Path = typer.Option(TRAIN_FEATURES_FILE, help="Path to training features CSV"),
    val_file: Path = typer.Option(VAL_FEATURES_FILE, help="Path to validation features CSV"),
    test_file: Path = typer.Option(TEST_FEATURES_FILE, help="Path to test features CSV"),
):
    """Load and inspect feature-engineered datasets."""
    logger.info("Loading feature-engineered datasets...")
    train_df, val_df, test_df = load_features(train_file, val_file, test_file)
    
    logger.info("\nPreparing features...")
    X_train, y_train, X_val, y_val, X_test, y_test = prepare_features(train_df, val_df, test_df)
    
    logger.success("✓ Features loaded and prepared!")
    logger.info(f"Feature columns: {FEATURE_COLUMNS}")
    logger.info(f"Target column: {TARGET_COLUMN}")


if __name__ == "__main__":
    app()

